import { Component, computed, DestroyRef, inject, OnInit, signal } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { HttpErrorResponse } from '@angular/common/http';
import { ToastService } from '../../../../../shared/services/toast.service';

// Import of real models generated by your backend
import {
  SpecialtyControllerService,
  SpecialtyRequest,
  SpecialtyResponse
} from '../../../../../core/api';

@Component({
  selector: 'app-specialty',
  standalone: true,
  imports: [ReactiveFormsModule],
  templateUrl: './specialty.html',
  styleUrl: './specialty.css'
})
export class Specialty implements OnInit {
  private specialtyService = inject(SpecialtyControllerService);
  private toastService = inject(ToastService);
  private fb = inject(FormBuilder);
  private destroyRef = inject(DestroyRef);

  // --- STATE (Signals) ---
  specialties = signal<SpecialtyResponse[]>([]);
  isLoading = signal<boolean>(true);
  isModalOpen = signal<boolean>(false);
  isSubmitting = signal<boolean>(false);
  editingSpecialtyId = signal<number | null>(null);

  // --- COMPUTED ---
  modalTitle = computed(() =>
    this.editingSpecialtyId() !== null ? 'Modifier la spécialité' : 'Ajouter une spécialité'
  );

  // --- FORM ---
  specialtyForm: FormGroup = this.fb.group({
    code: ['', [Validators.required]],
    label: ['', [Validators.required]]
  });

  ngOnInit(): void {
    this.loadSpecialties();
  }

  loadSpecialties(): void {
    this.isLoading.set(true);
    this.specialtyService
      .getAllSpecialties()
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (response: any) => {
          if (response.success) {
            this.specialties.set(response.data);
          } else {
            this.handleBackendError(response);
          }
          this.isLoading.set(false);
        },
        error: (err: HttpErrorResponse) => {
          this.handleBackendError(err.error);
          this.isLoading.set(false);
        }
      });
  }

  // OPEN MODAL: ADD
  openAddModal(): void {
    this.editingSpecialtyId.set(null);
    this.specialtyForm.reset();
    this.isModalOpen.set(true);
  }

  // OPEN MODAL: EDIT
  openEditModal(specialty: SpecialtyResponse): void {
    this.editingSpecialtyId.set(specialty.id!);
    this.specialtyForm.patchValue({
      code: specialty.code,
      label: specialty.label
    });
    this.isModalOpen.set(true);
  }

  closeModal(): void {
    this.isModalOpen.set(false);
    this.editingSpecialtyId.set(null);
    this.specialtyForm.reset();
  }

  onSubmit(): void {
    if (this.specialtyForm.invalid) {
      this.toastService.error('Veuillez remplir tous les champs obligatoires.');
      return;
    }

    this.isSubmitting.set(true);

    // We type the form data with SpecialtyRequest
    const requestPayload: SpecialtyRequest = this.specialtyForm.value;
    const currentId = this.editingSpecialtyId();

    const request$ =
      currentId !== null
        ? this.specialtyService.updateSpecialty(currentId, requestPayload)
        : this.specialtyService.createSpecialty(requestPayload);

    request$.pipe(takeUntilDestroyed(this.destroyRef)).subscribe({
      next: (res: any) => {
        if (res.success) {
          this.toastService.success(
            `Spécialité ${currentId !== null ? 'modifiée' : 'ajoutée'} avec succès`
          );
          this.closeModal();
          this.loadSpecialties();
        } else {
          this.handleBackendError(res);
        }
        this.isSubmitting.set(false);
      },
      error: (err: HttpErrorResponse) => {
        this.handleBackendError(err.error);
        this.isSubmitting.set(false);
      }
    });
  }

  private handleBackendError(payload: any): void {
    if (!payload) {
      this.toastService.error('Erreur de connexion au serveur.');
      return;
    }

    if (payload.errors && Array.isArray(payload.errors) && payload.errors.length > 0) {
      payload.errors.forEach((err: { field: string; message: string }) => {
        this.toastService.error(this.translateErrorCode(err.message));
      });
    } else if (payload.message) {
      this.toastService.error(this.translateErrorCode(payload.message));
    } else {
      this.toastService.error('Une erreur inattendue est survenue.');
    }
  }

  private translateErrorCode(errorCode: string): string {
    const errorDictionary: Record<string, string> = {
      SPECIALTY_NAME_ALREADY_EXISTS: 'Ce libellé de spécialité est déjà utilisé.',
      SPECIALTY_CODE_ALREADY_EXISTS: 'Ce code de spécialité est déjà utilisé.',
      VALIDATION_ERREUR: 'Veuillez corriger les erreurs de validation.'
    };
    return errorDictionary[errorCode] || errorCode;
  }
}
