package com.tiba.pts.modules.classmanagement.dto.request;

import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class ClassGroupRequest {

  @NotBlank(message = "NAME_REQUIRED")
  private String name;

  @NotNull(message = "CAPACITY_REQUIRED")
  @Min(value = 1, message = "CAPACITY_MUST_BE_GREATER_THAN_ZERO")
  private Integer capacity;

  @NotNull(message = "PROMOTION_ID_REQUIRED")
  private Long promotionId;

  /**
   * Custom setter to intercept the value and apply systematic trimming. Overrides the default
   * setter generated by Lombok.
   */
  public void setName(String name) {
    this.name = name != null ? name.trim() : null;
  }
}
