/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AcademicYearRequest } from '../model/models';
import { ApiResponseAcademicYearResponse } from '../model/models';
import { ApiResponseActiveAcademicYearResponse } from '../model/models';
import { ApiResponseListAcademicYearResponse } from '../model/models';
import { ApiResponseLong } from '../model/models';
import { ApiResponsePageResponseAcademicYearResponse } from '../model/models';
import { ApiResponseVoid } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AcademicYearControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint patch /api/v1/academic-years/{id}/activate
     * @param id 
     */
    activateAcademicYear(id: number, extraHttpRequestParams?: any): Observable<ApiResponseVoid>;

    /**
     * 
     * 
     * @endpoint patch /api/v1/academic-years/{id}/status
     * @param id 
     * @param newStatus 
     */
    changeAcademicYearStatus(id: number, newStatus: 'PLANNED' | 'IN_PROGRESS' | 'CLOSED', extraHttpRequestParams?: any): Observable<ApiResponseVoid>;

    /**
     * 
     * 
     * @endpoint post /api/v1/academic-years
     * @param academicYearRequest 
     */
    createAcademicYear(academicYearRequest: AcademicYearRequest, extraHttpRequestParams?: any): Observable<ApiResponseLong>;

    /**
     * 
     * 
     * @endpoint patch /api/v1/academic-years/{id}/deactivate
     * @param id 
     */
    deactivateAcademicYear(id: number, extraHttpRequestParams?: any): Observable<ApiResponseVoid>;

    /**
     * 
     * 
     * @endpoint get /api/v1/academic-years/{id}
     * @param id 
     */
    getAcademicYearById(id: number, extraHttpRequestParams?: any): Observable<ApiResponseAcademicYearResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/academic-years/active-or-planned
     */
    getActiveOrPlannedYears(extraHttpRequestParams?: any): Observable<ApiResponseListAcademicYearResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/academic-years
     * @param page 
     * @param size 
     */
    getAllAcademicYears(page?: number, size?: number, extraHttpRequestParams?: any): Observable<ApiResponsePageResponseAcademicYearResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/academic-years/current
     */
    getCurrentAcademicYear(extraHttpRequestParams?: any): Observable<ApiResponseAcademicYearResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/academic-years/active-year-info
     */
    getCurrentActiveSession(extraHttpRequestParams?: any): Observable<ApiResponseActiveAcademicYearResponse>;

    /**
     * 
     * 
     * @endpoint put /api/v1/academic-years/{id}
     * @param id 
     * @param academicYearRequest 
     */
    updateAcademicYear(id: number, academicYearRequest: AcademicYearRequest, extraHttpRequestParams?: any): Observable<ApiResponseLong>;

}
