/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AcademicYearDto } from '../model/models';
import { ApiResponseAcademicYearDto } from '../model/models';
import { ApiResponseActiveAcademicYearDTO } from '../model/models';
import { ApiResponseLong } from '../model/models';
import { ApiResponsePageResponseAcademicYearDto } from '../model/models';
import { ApiResponseVoid } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AcademicYearControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint patch /api/v1/academic-years/{id}/activate
     * @param id 
     */
    activateAcademicYear(id: number, extraHttpRequestParams?: any): Observable<ApiResponseVoid>;

    /**
     * 
     * 
     * @endpoint post /api/v1/academic-years
     * @param academicYearDto 
     */
    createAcademicYear(academicYearDto: AcademicYearDto, extraHttpRequestParams?: any): Observable<ApiResponseLong>;

    /**
     * 
     * 
     * @endpoint get /api/v1/academic-years/{id}
     * @param id 
     */
    getAcademicYearById(id: number, extraHttpRequestParams?: any): Observable<ApiResponseAcademicYearDto>;

    /**
     * 
     * 
     * @endpoint get /api/v1/academic-years/active
     */
    getActiveAcademicYear(extraHttpRequestParams?: any): Observable<ApiResponseAcademicYearDto>;

    /**
     * 
     * 
     * @endpoint get /api/v1/academic-years
     * @param page 
     * @param size 
     */
    getAllAcademicYears(page?: number, size?: number, extraHttpRequestParams?: any): Observable<ApiResponsePageResponseAcademicYearDto>;

    /**
     * 
     * 
     * @endpoint get /api/v1/academic-years/current-session
     */
    getCurrentSession(extraHttpRequestParams?: any): Observable<ApiResponseActiveAcademicYearDTO>;

    /**
     * 
     * 
     * @endpoint put /api/v1/academic-years/{id}
     * @param id 
     * @param academicYearDto 
     */
    updateAcademicYear(id: number, academicYearDto: AcademicYearDto, extraHttpRequestParams?: any): Observable<ApiResponseAcademicYearDto>;

}
