/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AcceleratedPromotionRequest } from '../model/models';
import { ApiResponseAcceleratedPromotionResponse } from '../model/models';
import { ApiResponseListAcceleratedPromotionResponse } from '../model/models';
import { ApiResponseLong } from '../model/models';
import { ApiResponseMapPromotionStatusLong } from '../model/models';
import { ApiResponsePageResponseAcceleratedPromotionResponse } from '../model/models';
import { ApiResponseVoid } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AcceleratedPromotionControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint patch /api/v1/promotions/accelerated/{id}/status
     * @param id 
     * @param status 
     */
    changeAcceleratedStatus(id: number, status: 'DRAFT' | 'ENROLLMENT' | 'IN_PROGRESS' | 'EVALUATION' | 'COMPLETED' | 'CANCELLED', extraHttpRequestParams?: any): Observable<ApiResponseVoid>;

    /**
     * 
     * 
     * @endpoint post /api/v1/promotions/accelerated
     * @param acceleratedPromotionRequest 
     */
    createAcceleratedPromotion(acceleratedPromotionRequest: AcceleratedPromotionRequest, extraHttpRequestParams?: any): Observable<ApiResponseLong>;

    /**
     * 
     * 
     * @endpoint get /api/v1/promotions/accelerated/{id}
     * @param id 
     */
    getAcceleratedPromotionById(id: number, extraHttpRequestParams?: any): Observable<ApiResponseAcceleratedPromotionResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/promotions/accelerated
     * @param page 
     * @param size 
     */
    getAllAcceleratedPromotions(page?: number, size?: number, extraHttpRequestParams?: any): Observable<ApiResponsePageResponseAcceleratedPromotionResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/promotions/accelerated/status/{status}
     * @param status 
     * @param limit 
     */
    getPromotionsByStatus1(status: 'DRAFT' | 'ENROLLMENT' | 'IN_PROGRESS' | 'EVALUATION' | 'COMPLETED' | 'CANCELLED', limit?: number, extraHttpRequestParams?: any): Observable<ApiResponseListAcceleratedPromotionResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/promotions/accelerated/status/counts
     */
    getStatusCounts(extraHttpRequestParams?: any): Observable<ApiResponseMapPromotionStatusLong>;

    /**
     * 
     * 
     * @endpoint put /api/v1/promotions/accelerated/{id}
     * @param id 
     * @param acceleratedPromotionRequest 
     */
    updateAcceleratedPromotion(id: number, acceleratedPromotionRequest: AcceleratedPromotionRequest, extraHttpRequestParams?: any): Observable<ApiResponseLong>;

}
