/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AccreditedPromotionRequest } from '../model/models';
import { AccreditedPromotionUpdateRequest } from '../model/models';
import { ApiResponseAccreditedPromotionResponse } from '../model/models';
import { ApiResponseListAccreditedPromotionResponse } from '../model/models';
import { ApiResponseListAccreditedPromotionStatsResponse } from '../model/models';
import { ApiResponseListOngoingPromotionResponse } from '../model/models';
import { ApiResponseLong } from '../model/models';
import { ApiResponsePageResponseAccreditedPromotionResponse } from '../model/models';
import { ApiResponseVoid } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AccreditedPromotionControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint patch /api/v1/promotions/accredited/{id}/status
     * @param id 
     * @param status 
     */
    changePromotionStatus(id: number, status: 'DRAFT' | 'ENROLLMENT' | 'IN_PROGRESS' | 'EVALUATION' | 'COMPLETED' | 'CANCELLED', extraHttpRequestParams?: any): Observable<ApiResponseVoid>;

    /**
     * 
     * 
     * @endpoint post /api/v1/promotions/accredited
     * @param accreditedPromotionRequest 
     */
    createAccreditedPromotion(accreditedPromotionRequest: AccreditedPromotionRequest, extraHttpRequestParams?: any): Observable<ApiResponseLong>;

    /**
     * 
     * 
     * @endpoint get /api/v1/promotions/accredited/{id}
     * @param id 
     */
    getAccreditedPromotionById(id: number, extraHttpRequestParams?: any): Observable<ApiResponseAccreditedPromotionResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/promotions/accredited/statistics
     */
    getAccreditedPromotionStatistics(extraHttpRequestParams?: any): Observable<ApiResponseListAccreditedPromotionStatsResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/promotions/accredited
     * @param page 
     * @param size 
     */
    getAllAccreditedPromotions(page?: number, size?: number, extraHttpRequestParams?: any): Observable<ApiResponsePageResponseAccreditedPromotionResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/promotions/accredited/ongoing
     * @param limit 
     */
    getOngoingPromotions(limit?: number, extraHttpRequestParams?: any): Observable<ApiResponseListOngoingPromotionResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/promotions/accredited/status/{status}
     * @param status 
     * @param limit 
     */
    getPromotionsByStatus(status: 'DRAFT' | 'ENROLLMENT' | 'IN_PROGRESS' | 'EVALUATION' | 'COMPLETED' | 'CANCELLED', limit?: number, extraHttpRequestParams?: any): Observable<ApiResponseListAccreditedPromotionResponse>;

    /**
     * 
     * 
     * @endpoint put /api/v1/promotions/accredited/{id}
     * @param id 
     * @param accreditedPromotionUpdateRequest 
     */
    updateAccreditedPromotion(id: number, accreditedPromotionUpdateRequest: AccreditedPromotionUpdateRequest, extraHttpRequestParams?: any): Observable<ApiResponseLong>;

}
