export * from './academic-year-controller.service';
import { AcademicYearControllerService } from './academic-year-controller.service';
export * from './academic-year-controller.serviceInterface';
export * from './auth-controller.service';
import { AuthControllerService } from './auth-controller.service';
export * from './auth-controller.serviceInterface';
export * from './enrollment-controller.service';
import { EnrollmentControllerService } from './enrollment-controller.service';
export * from './enrollment-controller.serviceInterface';
export * from './exam-session-controller.service';
import { ExamSessionControllerService } from './exam-session-controller.service';
export * from './exam-session-controller.serviceInterface';
export * from './level-controller.service';
import { LevelControllerService } from './level-controller.service';
export * from './level-controller.serviceInterface';
export * from './registration-document-controller.service';
import { RegistrationDocumentControllerService } from './registration-document-controller.service';
export * from './registration-document-controller.serviceInterface';
export * from './specialty-controller.service';
import { SpecialtyControllerService } from './specialty-controller.service';
export * from './specialty-controller.serviceInterface';
export * from './term-controller.service';
import { TermControllerService } from './term-controller.service';
export * from './term-controller.serviceInterface';
export * from './training-session-controller.service';
import { TrainingSessionControllerService } from './training-session-controller.service';
export * from './training-session-controller.serviceInterface';
export const APIS = [AcademicYearControllerService, AuthControllerService, EnrollmentControllerService, ExamSessionControllerService, LevelControllerService, RegistrationDocumentControllerService, SpecialtyControllerService, TermControllerService, TrainingSessionControllerService];
