export * from './academic-year-controller.service';
import { AcademicYearControllerService } from './academic-year-controller.service';
export * from './academic-year-controller.serviceInterface';
export * from './accelerated-promotion-controller.service';
import { AcceleratedPromotionControllerService } from './accelerated-promotion-controller.service';
export * from './accelerated-promotion-controller.serviceInterface';
export * from './accredited-promotion-controller.service';
import { AccreditedPromotionControllerService } from './accredited-promotion-controller.service';
export * from './accredited-promotion-controller.serviceInterface';
export * from './auth-controller.service';
import { AuthControllerService } from './auth-controller.service';
export * from './auth-controller.serviceInterface';
export * from './continuous-promotion-controller.service';
import { ContinuousPromotionControllerService } from './continuous-promotion-controller.service';
export * from './continuous-promotion-controller.serviceInterface';
export * from './enrollment-controller.service';
import { EnrollmentControllerService } from './enrollment-controller.service';
export * from './enrollment-controller.serviceInterface';
export * from './enrollment-document-controller.service';
import { EnrollmentDocumentControllerService } from './enrollment-document-controller.service';
export * from './enrollment-document-controller.serviceInterface';
export * from './exam-session-controller.service';
import { ExamSessionControllerService } from './exam-session-controller.service';
export * from './exam-session-controller.serviceInterface';
export * from './holiday-controller.service';
import { HolidayControllerService } from './holiday-controller.service';
export * from './holiday-controller.serviceInterface';
export * from './level-controller.service';
import { LevelControllerService } from './level-controller.service';
export * from './level-controller.serviceInterface';
export * from './parent-controller.service';
import { ParentControllerService } from './parent-controller.service';
export * from './parent-controller.serviceInterface';
export * from './period-controller.service';
import { PeriodControllerService } from './period-controller.service';
export * from './period-controller.serviceInterface';
export * from './promotion-controller.service';
import { PromotionControllerService } from './promotion-controller.service';
export * from './promotion-controller.serviceInterface';
export * from './promotion-subject-controller.service';
import { PromotionSubjectControllerService } from './promotion-subject-controller.service';
export * from './promotion-subject-controller.serviceInterface';
export * from './ref-teacher-specialty-controller.service';
import { RefTeacherSpecialtyControllerService } from './ref-teacher-specialty-controller.service';
export * from './ref-teacher-specialty-controller.serviceInterface';
export * from './specialty-controller.service';
import { SpecialtyControllerService } from './specialty-controller.service';
export * from './specialty-controller.serviceInterface';
export * from './student-controller.service';
import { StudentControllerService } from './student-controller.service';
export * from './student-controller.serviceInterface';
export * from './subject-controller.service';
import { SubjectControllerService } from './subject-controller.service';
export * from './subject-controller.serviceInterface';
export * from './teacher-controller.service';
import { TeacherControllerService } from './teacher-controller.service';
export * from './teacher-controller.serviceInterface';
export * from './training-controller.service';
import { TrainingControllerService } from './training-controller.service';
export * from './training-controller.serviceInterface';
export * from './user-controller.service';
import { UserControllerService } from './user-controller.service';
export * from './user-controller.serviceInterface';
export const APIS = [AcademicYearControllerService, AcceleratedPromotionControllerService, AccreditedPromotionControllerService, AuthControllerService, ContinuousPromotionControllerService, EnrollmentControllerService, EnrollmentDocumentControllerService, ExamSessionControllerService, HolidayControllerService, LevelControllerService, ParentControllerService, PeriodControllerService, PromotionControllerService, PromotionSubjectControllerService, RefTeacherSpecialtyControllerService, SpecialtyControllerService, StudentControllerService, SubjectControllerService, TeacherControllerService, TrainingControllerService, UserControllerService];
