/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseListAssessmentLookupResponse } from '../model/models';
import { ApiResponseListAssessmentResponse } from '../model/models';
import { ApiResponseLong } from '../model/models';
import { ApiResponseVoid } from '../model/models';
import { AssessmentRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AssessmentControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint patch /api/v1/assessments/{id}/cancel
     * @param id 
     */
    cancelAssessment(id: number, extraHttpRequestParams?: any): Observable<ApiResponseVoid>;

    /**
     * 
     * 
     * @endpoint post /api/v1/assessments
     * @param assessmentRequest 
     */
    createAssessment(assessmentRequest: AssessmentRequest, extraHttpRequestParams?: any): Observable<ApiResponseLong>;

    /**
     * 
     * 
     * @endpoint delete /api/v1/assessments/{id}
     * @param id 
     */
    deleteAssessment(id: number, extraHttpRequestParams?: any): Observable<ApiResponseVoid>;

    /**
     * 
     * 
     * @endpoint get /api/v1/assessments/promotion-subject/{promotionSubjectId}
     * @param promotionSubjectId 
     */
    getAssessmentsByPromotionSubject(promotionSubjectId: number, extraHttpRequestParams?: any): Observable<ApiResponseListAssessmentResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/assessments/promotion-subject/{promotionSubjectId}/grading
     * @param promotionSubjectId 
     */
    getGradingAssessmentsByPromotionSubject(promotionSubjectId: number, extraHttpRequestParams?: any): Observable<ApiResponseListAssessmentResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/assessments/timetable/{timetableId}/unscheduled
     * @param timetableId 
     */
    getUnscheduledAssessmentsForTimetable(timetableId: number, extraHttpRequestParams?: any): Observable<ApiResponseListAssessmentLookupResponse>;

    /**
     * 
     * 
     * @endpoint patch /api/v1/assessments/{id}/lock
     * @param id 
     */
    lockAssessment(id: number, extraHttpRequestParams?: any): Observable<ApiResponseVoid>;

    /**
     * 
     * 
     * @endpoint patch /api/v1/assessments/{id}/mark-planned
     * @param id 
     */
    markAsPlanned(id: number, extraHttpRequestParams?: any): Observable<ApiResponseVoid>;

    /**
     * 
     * 
     * @endpoint patch /api/v1/assessments/{id}/open-grading
     * @param id 
     */
    openForGrading(id: number, extraHttpRequestParams?: any): Observable<ApiResponseVoid>;

    /**
     * 
     * 
     * @endpoint patch /api/v1/assessments/{id}/publish
     * @param id 
     */
    publishAssessment(id: number, extraHttpRequestParams?: any): Observable<ApiResponseVoid>;

    /**
     * 
     * 
     * @endpoint patch /api/v1/assessments/{id}/reject-return-to-teacher
     * @param id 
     */
    rejectAndReturnToTeacher(id: number, extraHttpRequestParams?: any): Observable<ApiResponseVoid>;

    /**
     * 
     * 
     * @endpoint patch /api/v1/assessments/{id}/submit-to-admin
     * @param id 
     */
    submitToAdmin(id: number, extraHttpRequestParams?: any): Observable<ApiResponseVoid>;

    /**
     * 
     * 
     * @endpoint put /api/v1/assessments/{id}
     * @param id 
     * @param assessmentRequest 
     */
    updateAssessment(id: number, assessmentRequest: AssessmentRequest, extraHttpRequestParams?: any): Observable<ApiResponseLong>;

}
