/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseListAssessmentLookupResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AssessmentControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/v1/assessments/timetable/{timetableId}/unscheduled
     * @param timetableId 
     */
    getUnscheduledAssessmentsForTimetable(timetableId: number, extraHttpRequestParams?: any): Observable<ApiResponseListAssessmentLookupResponse>;

}
