/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseAttendanceStatsResponse } from '../model/models';
import { ApiResponseListStudentAttendanceResponse } from '../model/models';
import { ApiResponseLong } from '../model/models';
import { AttendanceRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AttendanceRecordControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/v1/attendances/session/{courseSessionId}/stats
     * @param courseSessionId 
     */
    getAttendanceStats(courseSessionId: number, extraHttpRequestParams?: any): Observable<ApiResponseAttendanceStatsResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/attendances/session/{courseSessionId}/students
     * @param courseSessionId 
     */
    getStudentsAttendanceForSession(courseSessionId: number, extraHttpRequestParams?: any): Observable<ApiResponseListStudentAttendanceResponse>;

    /**
     * 
     * 
     * @endpoint post /api/v1/attendances
     * @param attendanceRequest 
     */
    submitAttendance(attendanceRequest: AttendanceRequest, extraHttpRequestParams?: any): Observable<ApiResponseLong>;

}
