/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AuthRequest } from '../model/models';
import { AuthResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/auth/login
     * @param authRequest 
     */
    login(authRequest: AuthRequest, extraHttpRequestParams?: any): Observable<AuthResponse>;

}
