/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseClassGroupDetailResponse } from '../model/models';
import { ApiResponseClassManagementStatsResponse } from '../model/models';
import { ApiResponseListClassGroupResponse } from '../model/models';
import { ApiResponseLong } from '../model/models';
import { ClassGroupRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ClassGroupControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/v1/class-groups
     * @param classGroupRequest 
     */
    createClassGroup(classGroupRequest: ClassGroupRequest, extraHttpRequestParams?: any): Observable<ApiResponseLong>;

    /**
     * 
     * 
     * @endpoint get /api/v1/class-groups/{id}/export/pdf
     * @param id 
     */
    exportPdf1(id: number, extraHttpRequestParams?: any): Observable<string>;

    /**
     * 
     * 
     * @endpoint get /api/v1/class-groups/{id}/export/pdf/documents
     * @param id 
     * @param documentIds 
     */
    exportPdfWithDocuments(id: number, documentIds: Array<number>, extraHttpRequestParams?: any): Observable<string>;

    /**
     * 
     * 
     * @endpoint get /api/v1/class-groups
     * @param levelId 
     * @param trainingId 
     * @param status 
     */
    getAllClassGroups(levelId?: number, trainingId?: number, status?: 'DRAFT' | 'ACTIVE' | 'INACTIVE' | 'ARCHIVED', extraHttpRequestParams?: any): Observable<ApiResponseListClassGroupResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/class-groups/{id}/details
     * @param id 
     */
    getClassGroupDetails(id: number, extraHttpRequestParams?: any): Observable<ApiResponseClassGroupDetailResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/class-groups/stats
     */
    getClassManagementStats(extraHttpRequestParams?: any): Observable<ApiResponseClassManagementStatsResponse>;

    /**
     * 
     * 
     * @endpoint patch /api/v1/class-groups/{id}/status
     * @param id 
     * @param status 
     */
    updateClassGroupStatus(id: number, status: 'DRAFT' | 'ACTIVE' | 'INACTIVE' | 'ARCHIVED', extraHttpRequestParams?: any): Observable<ApiResponseLong>;

}
