/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseBoolean } from '../model/models';
import { ApiResponseEnrollmentResponse } from '../model/models';
import { ApiResponseListUnassignedEnrollmentResponse } from '../model/models';
import { ApiResponseVoid } from '../model/models';
import { EnrollmentRequest } from '../model/models';
import { EnrollmentResponse } from '../model/models';
import { EnrollmentSearchRequest } from '../model/models';
import { PageResponseEnrollmentListResponse } from '../model/models';
import { UnassignedEnrollmentSearchRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface EnrollmentControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/v1/enrollments/check-existence
     * @param studentId 
     * @param promotionId 
     */
    checkStudentEnrollmentExistence(studentId: number, promotionId: number, extraHttpRequestParams?: any): Observable<ApiResponseBoolean>;

    /**
     * 
     * 
     * @endpoint post /api/v1/enrollments
     * @param enrollmentRequest 
     */
    createEnrollment(enrollmentRequest: EnrollmentRequest, extraHttpRequestParams?: any): Observable<ApiResponseEnrollmentResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/enrollments/{id}/export/pdf
     * @param id 
     */
    exportPdf(id: number, extraHttpRequestParams?: any): Observable<string>;

    /**
     * 
     * 
     * @endpoint get /api/v1/enrollments
     * @param filterRequest 
     */
    getAllEnrollments(filterRequest: EnrollmentSearchRequest, extraHttpRequestParams?: any): Observable<PageResponseEnrollmentListResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/enrollments/{id}
     * @param id 
     */
    getEnrollmentById(id: number, extraHttpRequestParams?: any): Observable<EnrollmentResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/enrollments/unassigned
     * @param filterRequest 
     */
    getUnassignedValidatedEnrollments(filterRequest: UnassignedEnrollmentSearchRequest, extraHttpRequestParams?: any): Observable<ApiResponseListUnassignedEnrollmentResponse>;

    /**
     * 
     * 
     * @endpoint patch /api/v1/enrollments/documents/{submissionId}/toggle-status
     * @param submissionId 
     */
    toggleDocumentStatus(submissionId: number, extraHttpRequestParams?: any): Observable<ApiResponseVoid>;

    /**
     * 
     * 
     * @endpoint patch /api/v1/enrollments/{id}/status/{status}
     * @param id 
     * @param status 
     */
    updateStatus(id: number, status: 'PRE_ENROLLED' | 'INCOMPLETE' | 'WAITLISTED' | 'CONDITIONALLY_VALIDATED' | 'VALIDATED' | 'SUSPENDED' | 'DROPPED_OUT' | 'REJECTED' | 'CANCELLED' | 'COMPLETED', extraHttpRequestParams?: any): Observable<ApiResponseVoid>;

}
