/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseListEnrollmentDocumentResponse } from '../model/models';
import { ApiResponseLong } from '../model/models';
import { EnrollmentDocumentRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface EnrollmentDocumentControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/v1/enrollment-documents
     * @param enrollmentDocumentRequest 
     */
    createDocument(enrollmentDocumentRequest: EnrollmentDocumentRequest, extraHttpRequestParams?: any): Observable<ApiResponseLong>;

    /**
     * 
     * 
     * @endpoint get /api/v1/enrollment-documents
     */
    getAllDocuments(extraHttpRequestParams?: any): Observable<ApiResponseListEnrollmentDocumentResponse>;

    /**
     * 
     * 
     * @endpoint put /api/v1/enrollment-documents/{id}
     * @param id 
     * @param enrollmentDocumentRequest 
     */
    updateDocument(id: number, enrollmentDocumentRequest: EnrollmentDocumentRequest, extraHttpRequestParams?: any): Observable<ApiResponseLong>;

}
