/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseListExamScheduleResponse } from '../model/models';
import { ApiResponseLong } from '../model/models';
import { ApiResponseVoid } from '../model/models';
import { ExamScheduleRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ExamScheduleControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/v1/exam-timetables/{timetableId}/schedules
     * @param timetableId 
     * @param examScheduleRequest 
     */
    createSchedule1(timetableId: number, examScheduleRequest: ExamScheduleRequest, extraHttpRequestParams?: any): Observable<ApiResponseLong>;

    /**
     * 
     * 
     * @endpoint get /api/v1/exam-timetables/{timetableId}/schedules
     * @param timetableId 
     */
    getSchedulesByTimetableId(timetableId: number, extraHttpRequestParams?: any): Observable<ApiResponseListExamScheduleResponse>;

    /**
     * 
     * 
     * @endpoint delete /api/v1/exam-timetables/schedules/{scheduleId}
     * @param scheduleId 
     */
    removeSchedule(scheduleId: number, extraHttpRequestParams?: any): Observable<ApiResponseVoid>;

    /**
     * 
     * 
     * @endpoint delete /api/v1/exam-schedules/{scheduleId}
     * @param scheduleId 
     */
    removeSchedule1(scheduleId: number, extraHttpRequestParams?: any): Observable<ApiResponseVoid>;

    /**
     * 
     * 
     * @endpoint put /api/v1/exam-timetables/schedules/{scheduleId}
     * @param scheduleId 
     * @param examScheduleRequest 
     */
    updateSchedule1(scheduleId: number, examScheduleRequest: ExamScheduleRequest, extraHttpRequestParams?: any): Observable<ApiResponseLong>;

    /**
     * 
     * 
     * @endpoint put /api/v1/exam-schedules/{scheduleId}
     * @param scheduleId 
     * @param examScheduleRequest 
     */
    updateSchedule2(scheduleId: number, examScheduleRequest: ExamScheduleRequest, extraHttpRequestParams?: any): Observable<ApiResponseLong>;

}
