/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseListExamSessionDto } from '../model/models';
import { ApiResponseLong } from '../model/models';
import { ExamSessionDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ExamSessionControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/v1/exam-sessions
     * @param examSessionDto 
     */
    createExamSession(examSessionDto: ExamSessionDto, extraHttpRequestParams?: any): Observable<ApiResponseLong>;

    /**
     * 
     * 
     * @endpoint get /api/v1/exam-sessions
     * @param termId 
     */
    getAllByTerm(termId: number, extraHttpRequestParams?: any): Observable<ApiResponseListExamSessionDto>;

}
