/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseListGradeRecordResponse } from '../model/models';
import { ApiResponseLong } from '../model/models';
import { ApiResponseVoid } from '../model/models';
import { GradeRecordRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface GradeRecordControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/v1/grades
     * @param gradeRecordRequest 
     */
    addGradeRecord(gradeRecordRequest: GradeRecordRequest, extraHttpRequestParams?: any): Observable<ApiResponseLong>;

    /**
     * 
     * 
     * @endpoint post /api/v1/grades/assessment/{assessmentId}
     * @param assessmentId 
     * @param gradeRecordRequest 
     */
    addGradeRecords(assessmentId: number, gradeRecordRequest: Array<GradeRecordRequest>, extraHttpRequestParams?: any): Observable<ApiResponseVoid>;

    /**
     * 
     * 
     * @endpoint get /api/v1/grades/assessment/{assessmentId}
     * @param assessmentId 
     */
    getAllGradesByAssessment(assessmentId: number, extraHttpRequestParams?: any): Observable<ApiResponseListGradeRecordResponse>;

}
