/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseHolidayResponse } from '../model/models';
import { ApiResponseListHolidayResponse } from '../model/models';
import { ApiResponseLong } from '../model/models';
import { HolidayRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface HolidayControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/v1/holidays
     * @param holidayRequest 
     */
    createHoliday(holidayRequest: HolidayRequest, extraHttpRequestParams?: any): Observable<ApiResponseLong>;

    /**
     * 
     * 
     * @endpoint get /api/v1/holidays/all
     */
    getAllHolidaysUnpaged(extraHttpRequestParams?: any): Observable<ApiResponseListHolidayResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/holidays/academic-year/{academicYearId}
     * @param academicYearId 
     */
    getHolidaysByAcademicYearId(academicYearId: number, extraHttpRequestParams?: any): Observable<ApiResponseListHolidayResponse>;

    /**
     * 
     * 
     * @endpoint put /api/v1/holidays/{id}
     * @param id 
     * @param holidayRequest 
     */
    updateHoliday(id: number, holidayRequest: HolidayRequest, extraHttpRequestParams?: any): Observable<ApiResponseHolidayResponse>;

}
