/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseListLevelResponse } from '../model/models';
import { ApiResponseLong } from '../model/models';
import { LevelRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface LevelControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/v1/levels
     * @param levelRequest 
     */
    createLevel(levelRequest: LevelRequest, extraHttpRequestParams?: any): Observable<ApiResponseLong>;

    /**
     * 
     * 
     * @endpoint get /api/v1/levels
     */
    getAllLevels(extraHttpRequestParams?: any): Observable<ApiResponseListLevelResponse>;

    /**
     * 
     * 
     * @endpoint put /api/v1/levels/{id}
     * @param id 
     * @param levelRequest 
     */
    updateLevel(id: number, levelRequest: LevelRequest, extraHttpRequestParams?: any): Observable<ApiResponseLong>;

}
