/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseExistenceCheckResponse } from '../model/models';
import { ApiResponseListParentResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ParentControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/v1/profiles/parents/check-existence
     * @param email 
     * @param phone 
     */
    checkParentExistence(email?: string, phone?: string, extraHttpRequestParams?: any): Observable<ApiResponseExistenceCheckResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/profiles/parents/search
     * @param keyword 
     */
    searchParents(keyword?: string, extraHttpRequestParams?: any): Observable<ApiResponseListParentResponse>;

}
