/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseListPeriodResponse } from '../model/models';
import { ApiResponseLong } from '../model/models';
import { ApiResponsePeriodResponse } from '../model/models';
import { PeriodRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PeriodControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/v1/periods
     * @param periodRequest 
     */
    createPeriod(periodRequest: PeriodRequest, extraHttpRequestParams?: any): Observable<ApiResponseLong>;

    /**
     * 
     * 
     * @endpoint get /api/v1/periods/academic-year/{academicYearId}
     * @param academicYearId 
     */
    getPeriodsByAcademicYearId(academicYearId: number, extraHttpRequestParams?: any): Observable<ApiResponseListPeriodResponse>;

    /**
     * 
     * 
     * @endpoint put /api/v1/periods/{id}
     * @param id 
     * @param periodRequest 
     */
    updatePeriod(id: number, periodRequest: PeriodRequest, extraHttpRequestParams?: any): Observable<ApiResponsePeriodResponse>;

}
