/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseListPromotionSubjectResponse } from '../model/models';
import { ApiResponseLong } from '../model/models';
import { ApiResponsePromotionStatsResponse } from '../model/models';
import { ApiResponseVoid } from '../model/models';
import { PromotionSubjectRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PromotionSubjectControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/v1/promotion-subjects
     * @param promotionSubjectRequest 
     */
    create(promotionSubjectRequest: PromotionSubjectRequest, extraHttpRequestParams?: any): Observable<ApiResponseLong>;

    /**
     * 
     * 
     * @endpoint delete /api/v1/promotion-subjects/{id}
     * @param id 
     */
    deletePromotionSubject(id: number, extraHttpRequestParams?: any): Observable<ApiResponseVoid>;

    /**
     * 
     * 
     * @endpoint get /api/v1/promotion-subjects/promotion/{promotionId}/stats
     * @param promotionId 
     */
    getPromotionStats(promotionId: number, extraHttpRequestParams?: any): Observable<ApiResponsePromotionStatsResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/promotion-subjects/promotion/{promotionId}/period/{periodId}
     * @param promotionId 
     * @param periodId 
     */
    getSubjectsByPromotionAndPeriod(promotionId: number, periodId: number, extraHttpRequestParams?: any): Observable<ApiResponseListPromotionSubjectResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/promotion-subjects/promotion/{promotionId}
     * @param promotionId 
     */
    getSubjectsByPromotionId(promotionId: number, extraHttpRequestParams?: any): Observable<ApiResponseListPromotionSubjectResponse>;

}
