/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseListRegistrationDocumentResponse } from '../model/models';
import { ApiResponseLong } from '../model/models';
import { RegistrationDocumentRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface RegistrationDocumentControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/v1/registration-documents
     * @param registrationDocumentRequest 
     */
    createDocument(registrationDocumentRequest: RegistrationDocumentRequest, extraHttpRequestParams?: any): Observable<ApiResponseLong>;

    /**
     * 
     * 
     * @endpoint get /api/v1/registration-documents
     */
    getAllDocuments(extraHttpRequestParams?: any): Observable<ApiResponseListRegistrationDocumentResponse>;

    /**
     * 
     * 
     * @endpoint put /api/v1/registration-documents/{id}
     * @param id 
     * @param registrationDocumentRequest 
     */
    updateDocument(id: number, registrationDocumentRequest: RegistrationDocumentRequest, extraHttpRequestParams?: any): Observable<ApiResponseLong>;

}
