/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseListRoomResponse } from '../model/models';
import { ApiResponseLong } from '../model/models';
import { ApiResponseRoomStatusStatsResponse } from '../model/models';
import { ApiResponseVoid } from '../model/models';
import { RoomRequest } from '../model/models';
import { RoomUpdateRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface RoomControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint patch /api/v1/rooms/{id}/status
     * @param id 
     * @param newStatus 
     */
    changeRoomStatus(id: number, newStatus: 'DRAFT' | 'ACTIVE' | 'MAINTENANCE' | 'ARCHIVED', extraHttpRequestParams?: any): Observable<ApiResponseVoid>;

    /**
     * 
     * 
     * @endpoint post /api/v1/rooms
     * @param roomRequest 
     */
    createRoom(roomRequest: RoomRequest, extraHttpRequestParams?: any): Observable<ApiResponseLong>;

    /**
     * 
     * 
     * @endpoint get /api/v1/rooms/active
     */
    getActiveRooms(extraHttpRequestParams?: any): Observable<ApiResponseListRoomResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/rooms
     */
    getAllRooms(extraHttpRequestParams?: any): Observable<ApiResponseListRoomResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/rooms/stats
     */
    getRoomStatusStats(extraHttpRequestParams?: any): Observable<ApiResponseRoomStatusStatsResponse>;

    /**
     * 
     * 
     * @endpoint put /api/v1/rooms/{id}
     * @param id 
     * @param roomUpdateRequest 
     */
    updateRoom(id: number, roomUpdateRequest: RoomUpdateRequest, extraHttpRequestParams?: any): Observable<ApiResponseLong>;

}
