/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseExistenceCheckResponse } from '../model/models';
import { ApiResponseListStudentResponse } from '../model/models';
import { ApiResponseLong } from '../model/models';
import { ApiResponsePageResponseStudentListResponse } from '../model/models';
import { ApiResponseStudentResponse } from '../model/models';
import { StudentRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface StudentControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/v1/profiles/students/check-existence
     * @param cin 
     * @param email 
     * @param phone 
     */
    checkExistence(cin?: string, email?: string, phone?: string, extraHttpRequestParams?: any): Observable<ApiResponseExistenceCheckResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/profiles/students/count/active
     */
    countActiveStudents(extraHttpRequestParams?: any): Observable<ApiResponseLong>;

    /**
     * 
     * 
     * @endpoint post /api/v1/profiles/students
     * @param studentRequest 
     */
    createStudent(studentRequest: StudentRequest, extraHttpRequestParams?: any): Observable<number>;

    /**
     * 
     * 
     * @endpoint get /api/v1/profiles/students/{id}
     * @param id 
     */
    getStudentById(id: number, extraHttpRequestParams?: any): Observable<ApiResponseStudentResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/profiles/students
     * @param page 
     * @param size 
     * @param keyword 
     * @param status 
     */
    getStudentsPaginated(page?: number, size?: number, keyword?: string, status?: 'PROSPECT' | 'ACTIVE' | 'SUSPENDED' | 'DROPPED_OUT' | 'ALUMNI', extraHttpRequestParams?: any): Observable<ApiResponsePageResponseStudentListResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/profiles/students/search
     * @param keyword 
     */
    searchStudents(keyword?: string, extraHttpRequestParams?: any): Observable<ApiResponseListStudentResponse>;

}
