/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseExistenceCheckResponse } from '../model/models';
import { ApiResponseListStudentResponse } from '../model/models';
import { StudentRequest } from '../model/models';
import { StudentResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface StudentControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/v1/profiles/students/check-existence
     * @param cin 
     * @param email 
     * @param phone 
     */
    checkExistence(cin?: string, email?: string, phone?: string, extraHttpRequestParams?: any): Observable<ApiResponseExistenceCheckResponse>;

    /**
     * 
     * 
     * @endpoint post /api/v1/profiles/students
     * @param studentRequest 
     */
    createStudent(studentRequest: StudentRequest, extraHttpRequestParams?: any): Observable<number>;

    /**
     * 
     * 
     * @endpoint get /api/v1/profiles/students/{id}
     * @param id 
     */
    getById(id: number, extraHttpRequestParams?: any): Observable<StudentResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/profiles/students/search
     * @param keyword 
     */
    searchStudents(keyword?: string, extraHttpRequestParams?: any): Observable<ApiResponseListStudentResponse>;

}
