/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseBoolean } from '../model/models';
import { ApiResponseListTrainingResponse } from '../model/models';
import { ApiResponseListTrainingTypeCountResponse } from '../model/models';
import { ApiResponseLong } from '../model/models';
import { ApiResponsePageResponseTrainingResponse } from '../model/models';
import { TrainingRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TrainingControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint patch /api/v1/trainings/{id}/change-activation
     * @param id 
     */
    changeTrainingActivation(id: number, extraHttpRequestParams?: any): Observable<ApiResponseBoolean>;

    /**
     * 
     * 
     * @endpoint post /api/v1/trainings
     * @param trainingRequest 
     */
    createTraining(trainingRequest: TrainingRequest, extraHttpRequestParams?: any): Observable<ApiResponseLong>;

    /**
     * 
     * 
     * @endpoint get /api/v1/trainings/stats/active-by-type
     */
    getActiveTrainingStats(extraHttpRequestParams?: any): Observable<ApiResponseListTrainingTypeCountResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/trainings/active
     * @param type 
     */
    getAllActiveTrainings(type?: 'CONTINUOUS' | 'ACCELERATED' | 'ACCREDITED', extraHttpRequestParams?: any): Observable<ApiResponseListTrainingResponse>;

    /**
     * 
     * 
     * @endpoint get /api/v1/trainings
     * @param page 
     * @param size 
     */
    getAllPaged(page?: number, size?: number, extraHttpRequestParams?: any): Observable<ApiResponsePageResponseTrainingResponse>;

    /**
     * 
     * 
     * @endpoint put /api/v1/trainings/{id}
     * @param id 
     * @param trainingRequest 
     */
    updateTraining(id: number, trainingRequest: TrainingRequest, extraHttpRequestParams?: any): Observable<ApiResponseLong>;

}
