/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseLong } from '../model/models';
import { ApiResponsePageResponseTrainingSessionResponse } from '../model/models';
import { TrainingSessionRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TrainingSessionControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/v1/training-sessions
     * @param trainingSessionRequest 
     */
    createTrainingSession(trainingSessionRequest: TrainingSessionRequest, extraHttpRequestParams?: any): Observable<ApiResponseLong>;

    /**
     * 
     * 
     * @endpoint get /api/v1/training-sessions
     * @param page 
     * @param size 
     */
    getPaginatedTrainingSessions(page?: number, size?: number, extraHttpRequestParams?: any): Observable<ApiResponsePageResponseTrainingSessionResponse>;

    /**
     * 
     * 
     * @endpoint put /api/v1/training-sessions/{id}
     * @param id 
     * @param trainingSessionRequest 
     */
    updateTrainingSession(id: number, trainingSessionRequest: TrainingSessionRequest, extraHttpRequestParams?: any): Observable<ApiResponseLong>;

}
