/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AdminChangePasswordRequest } from '../model/models';
import { ApiResponsePageResponseUserResponse } from '../model/models';
import { ApiResponseVoid } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UserControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint post /api/v1/users/{id}/archive
     * @param id 
     */
    archiveUser(id: number, extraHttpRequestParams?: any): Observable<ApiResponseVoid>;

    /**
     * 
     * 
     * @endpoint patch /api/v1/users/{id}/password
     * @param id 
     * @param adminChangePasswordRequest 
     */
    changePassword(id: number, adminChangePasswordRequest: AdminChangePasswordRequest, extraHttpRequestParams?: any): Observable<ApiResponseVoid>;

    /**
     * 
     * 
     * @endpoint get /api/v1/users
     * @param keyword 
     * @param role 
     * @param status 
     * @param page 
     * @param size 
     */
    getAllUsersPaged(keyword?: string, role?: 'ROLE_ADMIN' | 'ROLE_TEACHER' | 'ROLE_STUDENT' | 'ROLE_PARENT', status?: 'PENDING' | 'ACTIVE' | 'SUSPENDED' | 'ARCHIVED', page?: number, size?: number, extraHttpRequestParams?: any): Observable<ApiResponsePageResponseUserResponse>;

    /**
     * 
     * 
     * @endpoint post /api/v1/users/{id}/reactivate
     * @param id 
     */
    reactivateUser(id: number, extraHttpRequestParams?: any): Observable<ApiResponseVoid>;

    /**
     * 
     * 
     * @endpoint post /api/v1/users/{id}/suspend
     * @param id 
     */
    suspendUser(id: number, extraHttpRequestParams?: any): Observable<ApiResponseVoid>;

}
