/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AcceleratedPromotionResponse { 
    id?: number;
    name?: string;
    code?: string;
    startDate?: string;
    endDate?: string;
    status?: AcceleratedPromotionResponse.StatusEnum;
    fee?: number;
    trainingId?: number;
    trainingLabel?: string;
    specialityLabel?: string;
    enrollmentCount?: number;
    numberOfHours?: number;
    level?: string;
}
export namespace AcceleratedPromotionResponse {
    export const StatusEnum = {
        Planned: 'PLANNED',
        EnrollmentOpen: 'ENROLLMENT_OPEN',
        InProgress: 'IN_PROGRESS',
        Closed: 'CLOSED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


