/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccreditedPromotionUpdateRequest { 
    name: string;
    registrationOpeningDate: string;
    registrationDeadline: string;
    registrationFee: number;
    tuitionFee: number;
    capacity: number;
}

