/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ActiveAcademicYearResponse { 
    id?: number;
    label?: string;
    startDate?: string;
    endDate?: string;
    status?: ActiveAcademicYearResponse.StatusEnum;
    remainingDaysInYear?: number;
    currentPeriodLabel?: string;
    periodProgress?: number;
    remainingDaysInCurrentPeriod?: number;
}
export namespace ActiveAcademicYearResponse {
    export const StatusEnum = {
        Planned: 'PLANNED',
        Enrollment: 'ENROLLMENT',
        InProgress: 'IN_PROGRESS',
        Closing: 'CLOSING',
        Completed: 'COMPLETED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


