/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorDetail } from './error-detail';
import { ActiveAcademicYearDTO } from './active-academic-year-dto';


export interface ApiResponseActiveAcademicYearDTO { 
    success?: boolean;
    message?: string;
    errorCode?: string;
    data?: ActiveAcademicYearDTO;
    errors?: Array<ErrorDetail>;
    timestamp?: string;
}

