/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorDetail } from './error-detail';
import { PageResponseStudentListResponse } from './page-response-student-list-response';


export interface ApiResponsePageResponseStudentListResponse { 
    success?: boolean;
    message?: string;
    errorCode?: string;
    data?: PageResponseStudentListResponse;
    errors?: Array<ErrorDetail>;
    timestamp?: string;
}

