/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorDetail } from './error-detail';
import { TrainingTypeCountResponse } from './training-type-count-response';


export interface ApiResponseListTrainingTypeCountResponse { 
    success?: boolean;
    message?: string;
    errorCode?: string;
    data?: Array<TrainingTypeCountResponse>;
    errors?: Array<ErrorDetail>;
    timestamp?: string;
}

