/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorDetail } from './error-detail';
import { AuthData } from './auth-data';


export interface ApiResponseAuthData { 
    success?: boolean;
    message?: string;
    errorCode?: string;
    data?: AuthData;
    errors?: Array<ErrorDetail>;
    timestamp?: string;
}

