/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorDetail } from './error-detail';
import { PageResponseTrainingSessionResponse } from './page-response-training-session-response';


export interface ApiResponsePageResponseTrainingSessionResponse { 
    success?: boolean;
    message?: string;
    errorCode?: string;
    data?: PageResponseTrainingSessionResponse;
    errors?: Array<ErrorDetail>;
    timestamp?: string;
}

