/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorDetail } from './error-detail';
import { PageResponseAcceleratedPromotionResponse } from './page-response-accelerated-promotion-response';


export interface ApiResponsePageResponseAcceleratedPromotionResponse { 
    success?: boolean;
    message?: string;
    errorCode?: string;
    data?: PageResponseAcceleratedPromotionResponse;
    errors?: Array<ErrorDetail>;
    timestamp?: string;
}

