/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorDetail } from './error-detail';


export interface ApiResponseMapPromotionStatusLong { 
    success?: boolean;
    message?: string;
    errorCode?: string;
    data?: { [key: string]: number; };
    errors?: Array<ErrorDetail>;
    timestamp?: string;
}

