/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorDetail } from './error-detail';
import { PromotionStatsResponse } from './promotion-stats-response';


export interface ApiResponsePromotionStatsResponse { 
    success?: boolean;
    message?: string;
    errorCode?: string;
    data?: PromotionStatsResponse;
    errors?: Array<ErrorDetail>;
    timestamp?: string;
}

