/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorDetail } from './error-detail';
import { ClassGroupDetailResponse } from './class-group-detail-response';


export interface ApiResponseClassGroupDetailResponse { 
    success?: boolean;
    message?: string;
    errorCode?: string;
    data?: ClassGroupDetailResponse;
    errors?: Array<ErrorDetail>;
    timestamp?: string;
}

