/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorDetail } from './error-detail';
import { TermDto } from './term-dto';


export interface ApiResponseListTermDto { 
    success?: boolean;
    message?: string;
    errorCode?: string;
    data?: Array<TermDto>;
    errors?: Array<ErrorDetail>;
    timestamp?: string;
}

