/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorDetail } from './error-detail';
import { EnrollmentStatsResponse } from './enrollment-stats-response';


export interface ApiResponseEnrollmentStatsResponse { 
    success?: boolean;
    message?: string;
    errorCode?: string;
    data?: EnrollmentStatsResponse;
    errors?: Array<ErrorDetail>;
    timestamp?: string;
}

