/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AttendanceItemRequest { 
    enrollmentId: number;
    status: AttendanceItemRequest.StatusEnum;
}
export namespace AttendanceItemRequest {
    export const StatusEnum = {
        Absent: 'ABSENT',
        Present: 'PRESENT'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


