/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttendanceItemRequest } from './attendance-item-request';


export interface AttendanceRequest { 
    courseSessionId: number;
    isDraft: boolean;
    items: Array<AttendanceItemRequest>;
}

