/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthResponse { 
    success?: boolean;
    message?: string;
    data?: any | null;
    errorCode?: string;
    timestamp?: string;
}

