/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserInfo } from './user-info';


export interface AuthData { 
    token?: string;
    type?: string;
    expiresIn?: number;
    user?: UserInfo;
}

