/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContinuousPromotionRequest { 
    name: string;
    code: string;
    startDate: string;
    endDate: string;
    fee: number;
    trainingId: number;
    duration: number;
}

