/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CourseSessionRequest { 
    sessionDate: string;
    startTime: string;
    endTime: string;
    sessionType: CourseSessionRequest.SessionTypeEnum;
    lessonTitle?: string;
    courseContent?: string;
    classGroupId: number;
    subjectId: number;
    teacherId: number;
    roomId?: number;
}
export namespace CourseSessionRequest {
    export const SessionTypeEnum = {
        Regular: 'REGULAR',
        Replacement: 'REPLACEMENT',
        Support: 'SUPPORT',
        ExamSupervision: 'EXAM_SUPERVISION'
    } as const;
    export type SessionTypeEnum = typeof SessionTypeEnum[keyof typeof SessionTypeEnum];
}


