/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LevelSummaryResponse } from './level-summary-response';


export interface EnrollmentDocumentResponse { 
    id?: number;
    name?: string;
    quantity?: number;
    nature?: EnrollmentDocumentResponse.NatureEnum;
    condition?: EnrollmentDocumentResponse.ConditionEnum;
    levels?: Array<LevelSummaryResponse>;
    mandatory?: boolean;
}
export namespace EnrollmentDocumentResponse {
    export const NatureEnum = {
        Original: 'ORIGINAL',
        SimpleCopy: 'SIMPLE_COPY',
        CertifiedCopy: 'CERTIFIED_COPY',
        PhysicalFormat: 'PHYSICAL_FORMAT'
    } as const;
    export type NatureEnum = typeof NatureEnum[keyof typeof NatureEnum];
    export const ConditionEnum = {
        AllRegistrations: 'ALL_REGISTRATIONS',
        AdultStudent: 'ADULT_STUDENT',
        ForeignStudent: 'FOREIGN_STUDENT'
    } as const;
    export type ConditionEnum = typeof ConditionEnum[keyof typeof ConditionEnum];
}


