/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StudentInfoRequest } from './student-info-request';
import { SubmittedDocumentRequest } from './submitted-document-request';


export interface EnrollmentRequest { 
    type: EnrollmentRequest.TypeEnum;
    observation?: string;
    promotionId: number;
    enrollmentSubmittedDocuments: Array<SubmittedDocumentRequest>;
    studentInfo: StudentInfoRequest;
}
export namespace EnrollmentRequest {
    export const TypeEnum = {
        New: 'NEW',
        Repeater: 'REPEATER',
        Reintegration: 'REINTEGRATION'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


