/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EnrollmentResponse { 
    id?: number;
    studentFullName?: string;
    dateOfBirth?: string;
    studentPhoneNumber?: string;
    guardianPhoneNumber?: string;
    training?: string;
    promotionName?: string;
    enrollmentDate?: string;
    status?: EnrollmentResponse.StatusEnum;
}
export namespace EnrollmentResponse {
    export const StatusEnum = {
        Pending: 'PENDING',
        Validated: 'VALIDATED',
        Rejected: 'REJECTED',
        Cancelled: 'CANCELLED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


