/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubmittedDocumentResponse } from './submitted-document-response';
import { PromotionSummaryResponse } from './promotion-summary-response';
import { StudentSummaryResponse } from './student-summary-response';


export interface EnrollmentResponse { 
    id?: number;
    enrollmentNumber?: string;
    type?: EnrollmentResponse.TypeEnum;
    status?: EnrollmentResponse.StatusEnum;
    observation?: string;
    promotion?: PromotionSummaryResponse;
    student?: StudentSummaryResponse;
    enrollmentSubmittedDocuments?: Array<SubmittedDocumentResponse>;
}
export namespace EnrollmentResponse {
    export const TypeEnum = {
        New: 'NEW',
        Repeater: 'REPEATER',
        Reintegration: 'REINTEGRATION'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const StatusEnum = {
        PreEnrolled: 'PRE_ENROLLED',
        Incomplete: 'INCOMPLETE',
        Validated: 'VALIDATED',
        Rejected: 'REJECTED',
        Cancelled: 'CANCELLED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


