/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExamSessionResponse { 
    id?: number;
    label?: string;
    sessionType?: ExamSessionResponse.SessionTypeEnum;
    startDate?: string;
    endDate?: string;
    status?: ExamSessionResponse.StatusEnum;
    periodId?: number;
}
export namespace ExamSessionResponse {
    export const SessionTypeEnum = {
        Main: 'MAIN',
        Retake: 'RETAKE'
    } as const;
    export type SessionTypeEnum = typeof SessionTypeEnum[keyof typeof SessionTypeEnum];
    export const StatusEnum = {
        Open: 'OPEN',
        Closed: 'CLOSED',
        Locked: 'LOCKED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


