/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LevelDto { 
    id?: number;
    code: string;
    label: string;
    type: LevelDto.TypeEnum;
}
export namespace LevelDto {
    export const TypeEnum = {
        Accredited: 'ACCREDITED',
        Accelerated: 'ACCELERATED'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


