/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StudentAttendanceRecordResponse } from './student-attendance-record-response';


export interface PageResponseStudentAttendanceRecordResponse { 
    content?: Array<StudentAttendanceRecordResponse>;
    pageNumber?: number;
    pageSize?: number;
    totalElements?: number;
    totalPages?: number;
    isLast?: boolean;
}

