/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ParentDto { 
    firstName: string;
    lastName: string;
    phoneNumber: string;
    email?: string;
    dateOfBirth?: string;
    cin?: string;
    profession?: string;
    parentType?: ParentDto.ParentTypeEnum;
    maritalStatus?: ParentDto.MaritalStatusEnum;
    isDeceased?: boolean;
    isLegalGuardian: boolean;
}
export namespace ParentDto {
    export const ParentTypeEnum = {
        Father: 'FATHER',
        Mother: 'MOTHER',
        Guardian: 'GUARDIAN'
    } as const;
    export type ParentTypeEnum = typeof ParentTypeEnum[keyof typeof ParentTypeEnum];
    export const MaritalStatusEnum = {
        Single: 'SINGLE',
        Married: 'MARRIED',
        Divorced: 'DIVORCED',
        Widowed: 'WIDOWED'
    } as const;
    export type MaritalStatusEnum = typeof MaritalStatusEnum[keyof typeof MaritalStatusEnum];
}


