/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegistrationDocumentRequest { 
    name: string;
    quantity: number;
    nature: RegistrationDocumentRequest.NatureEnum;
    condition: RegistrationDocumentRequest.ConditionEnum;
    levelIds: Set<number>;
    isMandatory: boolean;
}
export namespace RegistrationDocumentRequest {
    export const NatureEnum = {
        Original: 'ORIGINAL',
        CopieSimple: 'COPIE_SIMPLE',
        CopieConforme: 'COPIE_CONFORME',
        FormatPhysique: 'FORMAT_PHYSIQUE'
    } as const;
    export type NatureEnum = typeof NatureEnum[keyof typeof NatureEnum];
    export const ConditionEnum = {
        ToutesInscriptions: 'TOUTES_INSCRIPTIONS',
        EleveMajeur: 'ELEVE_MAJEUR',
        EtudiantEtranger: 'ETUDIANT_ETRANGER'
    } as const;
    export type ConditionEnum = typeof ConditionEnum[keyof typeof ConditionEnum];
}


