/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StudentParentSummaryResponse } from './student-parent-summary-response';


export interface StudentSummaryResponse { 
    id?: number;
    studentCode?: string;
    firstName?: string;
    lastName?: string;
    cin?: string;
    phone?: string;
    parents?: Array<StudentParentSummaryResponse>;
}

