/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ParentInfoRequest } from './parent-info-request';


export interface StudentParentInfoRequest { 
    link: StudentParentInfoRequest.LinkEnum;
    parent: ParentInfoRequest;
    legalGuardian?: boolean;
    isLegalGuardian?: boolean;
}
export namespace StudentParentInfoRequest {
    export const LinkEnum = {
        Father: 'FATHER',
        Mother: 'MOTHER',
        Other: 'OTHER'
    } as const;
    export type LinkEnum = typeof LinkEnum[keyof typeof LinkEnum];
}


