/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StudentSiblingInfoRequest } from './student-sibling-info-request';
import { StudentParentInfoRequest } from './student-parent-info-request';


export interface StudentInfoRequest { 
    firstName: string;
    lastName: string;
    firstNameAr?: string;
    lastNameAr?: string;
    email?: string;
    phone?: string;
    cin?: string;
    id?: number;
    birthDate: string;
    birthPlace?: string;
    governorate?: string;
    delegation?: string;
    residenceAddress?: string;
    correspondenceAddress?: string;
    residence?: StudentInfoRequest.ResidenceEnum;
    parentsSituation?: StudentInfoRequest.ParentsSituationEnum;
    hasChronicDisease?: boolean;
    diseaseDescription?: string;
    studentSiblings?: Array<StudentSiblingInfoRequest>;
    parents?: Array<StudentParentInfoRequest>;
}
export namespace StudentInfoRequest {
    export const ResidenceEnum = {
        WithBothParents: 'WITH_BOTH_PARENTS',
        WithFatherOnly: 'WITH_FATHER_ONLY',
        WithMotherOnly: 'WITH_MOTHER_ONLY',
        WithRelatives: 'WITH_RELATIVES'
    } as const;
    export type ResidenceEnum = typeof ResidenceEnum[keyof typeof ResidenceEnum];
    export const ParentsSituationEnum = {
        LivingTogether: 'LIVING_TOGETHER',
        Separated: 'SEPARATED',
        FatherDeceased: 'FATHER_DECEASED',
        MotherDeceased: 'MOTHER_DECEASED',
        BothDeceased: 'BOTH_DECEASED'
    } as const;
    export type ParentsSituationEnum = typeof ParentsSituationEnum[keyof typeof ParentsSituationEnum];
}


