/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StudentListResponse { 
    id?: number;
    firstName?: string;
    lastName?: string;
    studentCode?: string;
    birthDate?: string;
    studentContact?: string;
    guardianContact?: string;
    status?: StudentListResponse.StatusEnum;
}
export namespace StudentListResponse {
    export const StatusEnum = {
        Prospect: 'PROSPECT',
        Active: 'ACTIVE',
        Suspended: 'SUSPENDED',
        DroppedOut: 'DROPPED_OUT',
        Alumni: 'ALUMNI'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


