/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ParentRequest } from './parent-request';


export interface StudentParentRequest { 
    link: StudentParentRequest.LinkEnum;
    parent: ParentRequest;
    legalGuardian?: boolean;
    isLegalGuardian?: boolean;
}
export namespace StudentParentRequest {
    export const LinkEnum = {
        Father: 'FATHER',
        Mother: 'MOTHER',
        Other: 'OTHER'
    } as const;
    export type LinkEnum = typeof LinkEnum[keyof typeof LinkEnum];
}


