/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ParentSummaryResponse } from './parent-summary-response';


export interface StudentParentSummaryResponse { 
    link?: StudentParentSummaryResponse.LinkEnum;
    parent?: ParentSummaryResponse;
    legalGuardian?: boolean;
}
export namespace StudentParentSummaryResponse {
    export const LinkEnum = {
        Father: 'FATHER',
        Mother: 'MOTHER',
        Other: 'OTHER'
    } as const;
    export type LinkEnum = typeof LinkEnum[keyof typeof LinkEnum];
}


