/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExamSessionDto } from './exam-session-dto';


export interface TermDto { 
    readonly id?: number;
    readonly createdAt?: string;
    readonly updatedAt?: string;
    name: string;
    startDate: string;
    endDate: string;
    academicYearId: number;
    examSessions?: Array<ExamSessionDto>;
}

