/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TrainingSessionRequest { 
    promotionName: string;
    academicYearId: number;
    expectedStartDate: string;
    estimatedEndDate: string;
    status: TrainingSessionRequest.StatusEnum;
    levelId: number;
    specialtyId: number;
    registrationOpenDate: string;
    registrationDeadline: string;
    registrationsOpen: boolean;
}
export namespace TrainingSessionRequest {
    export const StatusEnum = {
        InProgress: 'IN_PROGRESS',
        Finished: 'FINISHED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


