/**
 * Training school system Backend API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UnassignedEnrollmentSearchRequest { 
    promotionId?: number;
    firstName?: string;
    lastName?: string;
    cin?: string;
    phone?: string;
    studentCode?: string;
}

