import { Component, OnInit, inject, signal, computed } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import {
  AcademicYearControllerService,
  HolidayControllerService,
  HolidayRequest,
  AcademicYearResponse
} from '../../../../../core/api';
import { ToastService } from '../../../../../shared/services/toast.service';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-holiday',
  standalone: true,
  imports: [ReactiveFormsModule, CommonModule],
  templateUrl: './holiday.html',
  styleUrl: './holiday.css'
})
export class Holiday implements OnInit {
  private fb = inject(FormBuilder);
  private toast = inject(ToastService);
  private academicYearApi = inject(AcademicYearControllerService);
  private holidayApi = inject(HolidayControllerService);

  // --- GLOBAL STATES ---
  academicYears = signal<AcademicYearResponse[]>([]);
  selectedYearId = signal<number | null>(null);
  holidays = signal<any[]>([]);

  isLoading = signal<boolean>(true);
  isSaving = signal<boolean>(false);

  // --- MODAL STATES ---
  showHolidayModal = signal<boolean>(false);
  editingHolidayId = signal<number | null>(null);

  // --- FORM ---
  holidayForm = this.fb.group({
    label: ['', [Validators.required]],
    type: ['SCHOOL_BREAK', [Validators.required]],
    startDate: ['', [Validators.required]],
    endDate: ['']
  });

  // --- REACTIVE STATISTICS ---
  totalHolidayDays = computed(() => {
    return this.holidays().reduce((total, h) => total + (h.numberOfDays || 0), 0);
  });

  nextHoliday = computed(() => {
    const today = new Date().getTime();
    const upcoming = this.holidays()
      .filter(h => new Date(h.startDate).getTime() >= today)
      .sort((a, b) => new Date(a.startDate).getTime() - new Date(b.startDate).getTime());

    return upcoming.length > 0 ? upcoming[0] : null;
  });

  daysUntilNextHoliday = computed(() => {
    const next = this.nextHoliday();
    if (!next) return null;

    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const nextDate = new Date(next.startDate);

    const diffTime = nextDate.getTime() - today.getTime();
    return Math.ceil(diffTime / (1000 * 60 * 60 * 24));
  });

  ngOnInit() {
    this.loadOpenAcademicYears();
  }

  // ==========================================
  // DATA LOADING
  // ==========================================

  loadOpenAcademicYears() {
    this.isLoading.set(true);

    // Call the new API generated by Swagger
    this.academicYearApi.getOpenAcademicYears().subscribe({
      next: (res: any) => {
        // The API returns a list directly, so we use res.data (not .content)
        const years = res.data || [];
        this.academicYears.set(years);

        // Select the default year, or the first in the list if none is default
        const active = years.find((y: any) => y.isDefault) || years[0];

        if (active) {
          this.selectedYearId.set(active.id);
          this.loadHolidaysForYear(active.id);
        } else {
          // If the list of open years is completely empty
          this.isLoading.set(false);
        }
      },
      error: err => {
        this.toast.error('Erreur lors du chargement des années scolaires.');
        console.error('Erreur API OpenAcademicYears:', err);
        this.isLoading.set(false);
      }
    });
  }

  onYearChange(event: Event) {
    const yearId = Number((event.target as HTMLSelectElement).value);
    this.selectedYearId.set(yearId);
    this.loadHolidaysForYear(yearId);
  }

  loadHolidaysForYear(yearId: number) {
    this.isLoading.set(true);
    this.holidayApi.getHolidaysByAcademicYearId(yearId).subscribe({
      next: (res: any) => {
        this.holidays.set(res.data || []);
        this.isLoading.set(false);
      },
      error: () => {
        this.toast.error('Impossible de charger le calendrier des vacances.');
        this.holidays.set([]);
        this.isLoading.set(false);
      }
    });
  }

  // ==========================================
  // MODAL ACTIONS
  // ==========================================

  openModal() {
    this.editingHolidayId.set(null);
    this.holidayForm.reset({ type: 'SCHOOL_BREAK' });
    this.showHolidayModal.set(true);
  }

  editHoliday(holiday: any) {
    this.editingHolidayId.set(holiday.id);

    this.holidayForm.patchValue({
      label: holiday.label,
      type: holiday.type,
      startDate: this.formatDateForInput(holiday.startDate),
      endDate: this.formatDateForInput(holiday.endDate)
    });

    this.showHolidayModal.set(true);
  }

  closeModal() {
    this.showHolidayModal.set(false);
    this.editingHolidayId.set(null);
  }

  submitHoliday() {
    if (this.holidayForm.invalid) {
      this.holidayForm.markAllAsTouched();
      return;
    }

    const yearId = this.selectedYearId();
    if (!yearId) return;

    this.isSaving.set(true);

    // PAYLOAD PERFECTLY ALIGNED WITH YOUR JSON
    const payload: HolidayRequest = {
      label: this.holidayForm.value.label!,
      type: this.holidayForm.value.type! as any,
      startDate: this.holidayForm.value.startDate! as any,
      endDate: this.holidayForm.value.endDate! as any,
      academicYearId: yearId
    };

    const holidayId = this.editingHolidayId();

    if (holidayId) {
      this.holidayApi.updateHoliday(holidayId, payload).subscribe({
        next: () => {
          this.toast.success('Vacances modifiées avec succès');
          this.isSaving.set(false);
          this.closeModal();
          this.loadHolidaysForYear(yearId);
        },
        error: err => this.handleBackendError(err)
      });
    } else {
      this.holidayApi.createHoliday(payload).subscribe({
        next: () => {
          this.toast.success('Vacances ajoutées avec succès');
          this.isSaving.set(false);
          this.closeModal();
          this.loadHolidaysForYear(yearId);
        },
        error: err => this.handleBackendError(err)
      });
    }
  }

  // ==========================================
  // UTILITIES
  // ==========================================

  private handleBackendError(err: any) {
    this.isSaving.set(false);
    const errorBody = err?.error;

    if (errorBody?.errorCode === 'ENTITY_ALREADY_EXISTS') {
      this.toast.error('Une vacance avec ce libellé existe déjà pour cette année.');
    } else if (errorBody?.message === 'END_DATE_MUST_BE_AFTER_START_DATE') {
      this.toast.error('La date de fin doit être strictement après la date de début.');
    } else {
      this.toast.error("Erreur lors de l'enregistrement.");
    }
  }

  private formatDateForInput(dateValue: any): string {
    if (!dateValue) return '';
    if (typeof dateValue === 'string' && dateValue.length === 10) return dateValue;
    const d = new Date(dateValue);
    if (isNaN(d.getTime())) return '';
    return d.toISOString().split('T')[0];
  }

  getTypeBadgeClass(type: string): string {
    switch (type) {
      case 'PUBLIC_HOLIDAY':
        return 'bg-amber-100 text-amber-700 border-amber-200';
      case 'SCHOOL_BREAK':
        return 'bg-sky-100 text-sky-700 border-sky-200';
      case 'EXCEPTIONAL':
        return 'bg-rose-100 text-rose-700 border-rose-200';
      default:
        return 'bg-slate-100 text-slate-700 border-slate-200';
    }
  }

  getTypeLabel(type: string): string {
    switch (type) {
      case 'PUBLIC_HOLIDAY':
        return 'Jour Férié';
      case 'SCHOOL_BREAK':
        return 'Vacances Scolaires';
      case 'EXCEPTIONAL':
        return 'Fermeture Exceptionnelle';
      default:
        return type;
    }
  }
}
